apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
data:
  application.properties: |
    grpc.client.adservice.address=static://be-service:9090
    grpc.client.adservice.negotiationType=PLAINTEXT

    kafka.servers=kaffka-kafka.env.svc.cluster.local:9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  selector:
    matchLabels:
      app: fe-deployment
  template:
    metadata:
      labels:
        app: fe-deployment
    spec:
      containers:
      - name: fe-deployment
        image: "{{ .Values.image.fe.repository }}:{{ .Values.image.fe.tag }}"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: fe-config-volume
          mountPath: /config
      volumes:
        - name: fe-config-volume
          configMap:
            name: fe-config

---

apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: LoadBalancer
  selector:
    app: fe-deployment
  ports:
  - port: 8080
    targetPort: 8080


