apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
data:
  application.properties: |
    spring.data.cassandra.keyspace-name=advertisement
    spring.data.cassandra.contact-points=cassandra
    spring.data.cassandra.local-datacenter=datacenter1
    spring.data.cassandra.password=cassandra
    spring.data.cassandra.username=cassandra
    spring.data.cassandra.port=9042
    spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS
    kafka.servers=kaffka-kafka.nrhf.svc.cluster.local:9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-deployment
  template:
    metadata:
      labels:
        app: be-deployment
    spec:
      containers:
      - name: be-deployment
        image: roliiii/ad-be:1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: be-config-volume
          mountPath: /config
      volumes:
        - name: be-config-volume
          configMap:
            name: be-config

---

apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: be-deployment
  ports:
  - port: 9090
    targetPort: 9090


